import turtle
t=turtle.Turtle()
t.speed(5)
t.pensize(2)
t.forward(30)
t.left(180)
t.forward(30)
t.penup()
t.left(90)
t.forward(60)
t.left(90)
t.pendown()
t.forward(30)
t.right(90)
t.forward(20)
t.left(90)
t.forward(15)
for i in range(0,16):
    t.left(10)
    t.forward(10)
t.left(20)
t.forward(25)
t.left(90)
t.forward(114)
t.left(90)
t.forward(10)
t.penup()
for i in range(0,9):
    t.left(10)
    t.forward(10)
# Yarım çember için aynı döngü.
t.right(90)
t.forward(5)
t.pendown()
t.forward(60)
t.right(90)
t.forward(120)
t.right(90)
t.penup()
t.forward(300) # Buraya kadar And kapısını çizdirdik.
t.pendown()
t.right(180)
t.forward(30)
t.left(180)
t.forward(60)# Bir türlü 2 giriş ucunu OR KAPISINA birleştiremediğim uçların ilki.
t.left(90)
t.penup()
t.forward(30) # 2 uç arası mesafe
t.pendown()
t.left(90)
t.forward(60)# Birleştiremediğim uçların diğeri.
t.penup()
t.right(90)
t.forward(30)
t.left(90)
t.pendown()
for i in range(0,12): 
    t.left(5)
    t.forward(10)
t.left(50) # Nor kapısının diğer yarım çemberi için .
for i in range(0,12):  
    t.left(5)
    t.forward(10)
t.left(135)
for i in range(0,14):
    t.right(5)
    t.forward(10)
t.penup()
t.left(130)
for i in range(0,11): 
    t.left(5)
    t.forward(10)

t.right(60)
t.forward(15)
t.pendown()
t.circle(5)
t.forward(168)
t.left(90)
t.forward(40)
t.right(90)
t.forward(80)
t.right(90)
t.penup()
t.forward(20)
t.pendown()
for i in range(0,4): # Not kapısını çizdiriyoruz.
    t.left(120)
    t.forward(70)# üçgenin kenar uzunlukları
t.right(60)
t.circle(5)
t.left(30)
t.forward(70)
